[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Configuração do Monitor Serial
monitor_speed = 115200

; Diretivas de compilação para habilitar C++17 (necessário para std::optional)
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

; Gerenciador de Dependências Automático
lib_deps =
    ; Leitor RFID
    miguelbalboa/MFRC522 @ ^1.4.11
    
    ; Comunicação MQTT e manipulação de pacotes JSON
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.4
    
    ; Display OLED e dependência gráfica obrigatória da Adafruit
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9

    ; Wifi manager
    https://github.com/tzapu/WiFiManager.git